### ISSUE TITLE
Speed higher-order multiplications

### ISSUE THREAD

**Issue by MichielStock** [MichielStock/Kronecker.jl#43]
The vec trick still seems to work for higher-order Kronecker products, by means of recursion, e.g.

```julia
A = B = C = randn(10, 10);
x = rand(1000)

kronecker(A, B, C) * x
```
works.

I think however that there is still room for performance improvement, especially when all the components of the product are square and for higher-order products. In this case, the array containing the partial results have the same size, so a new one should not be allocated every step. Especially [TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl) seems much faster. 

Either have a specialized method that allocates a single array to store the results or use an external package?

**Comment by willtebbutt** [comment]
Maybe better to rely on an external package if possible for this? Generally better to re-use existing infrastructure than roll our own.

**Comment by MichielStock** [comment]
My main issue with using `TensorOperations.jl` is that it is much less general than `Kronecker.jl`. This makes it not possible to work with reshaped matrices or use `Zygote` for machine learning purposes.

**Comment by emerali** [comment]
Generalizing the vec-trick to  >2 factors is possible (see: http://yoksis.bilkent.edu.tr/pdf/files/11666.pdf)

I recently implemented this algorithm for the LazyArrays.jl package and could contribute to this package as well. However, in order to implement this algorithm I think we'd need to re-define the kronecker product type to store the factors in a vector (or tuple) instead of defining the type recursively.

On a related note, we should be able to build a specialized matmul for KronPow types as well which would amount to a generalization of the Fast-Walsh Hadamard transform: https://en.wikipedia.org/wiki/Fast_Walsh%E2%80%93Hadamard_transform

**Comment by MichielStock** [comment]
Did not know the shuffle algorithm. Thanks for bringing this to my attention.

I am a bit cautious in moving from the recursive definition to just keeping an array of matrices. The latter has some advantages in keeping the types of individual elements. Unless there is a very good reason to rewrite everything I would like to keep it so.

Getting the individual matrices of a `KroneckerProduct` is quite simple though. Maybe you could provide me with an implementation of the shuffle algorithm and I can look at how to incorporate it in the codebase?

When this works, we should indeed make specialized methods for special cases, such as Kronecker powers.
