### ISSUE TITLE
AbstractArray or AbstractMatrix or ??

### ISSUE THREAD

**Issue by JeffFessler** [MichielStock/Kronecker.jl#5]
This is a very interesting package!

* An `AbstractArray` can have any number of dimensions whereas an `AbstractMatrix` is 2D so I suspect you want the latter given the way you use `size()` in the code.

* It would be nice if this also worked with `LinearMaps` as well because all that is really needed here is matrix multiplication, not the full capabilities of an `AbstractArray` I think.
Unfortunately, `LinearMaps` are not a subtype of `AbstractMatrix` and its maintainers do not want to make it such a subtype so supporting `LinearMaps` here would require a `Union` or duck typing.  See:
https://github.com/Jutho/LinearMaps.jl/issues/38

**Comment by MichielStock** [comment]
Thanks for the suggestion. Kronecker products are always matrices, so `AbstractMatrix` is definitely more appropriate. 

I should work to integrate with `LinearMaps` as well, as my package and `LinearMaps` have a similar philosophy and it is the idea to have easy compatibility with other mathematical operations. At some point I should have a coffee with @Jutho since he works in the same university and there is some overlap with his packages and what I am trying to do.

**Comment by JeffFessler** [comment]
Small world!

**Comment by Jutho** [comment]
Unfortunately I don't drink coffee. But tea is fine :-) (when temperatures are less high and the semester is over).

**Comment by JeffFessler** [comment]
@MichielStock, fyi I have created an overlay for `LinearMaps` that is a subtype of `AbstractMatrix`, so it can be used with your `Kronecker` package (among other uses).  See:
https://github.com/JeffFessler/LinearMapsAA.jl
